In [ ]:
import torch

In [ ]:
x = torch.tensor([1,2,3])

In [ ]:
print(x)

tensor([1, 2, 3])


In [ ]:
x

tensor([1, 2, 3])

In [ ]:
shape = (2,3)

ones = torch.ones(shape)
zeros = torch.zeros(shape)

print(f'Ones tensor: \n {ones} \n')
print(f'Zeros tensor: \n {zeros}')

Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
random = torch.rand(shape)
print(random)

tensor([[0.9666, 0.3024, 0.5832],
        [0.7896, 0.6749, 0.6224]])


In [ ]:
y = torch.rand(shape, dtype=torch.float)
print(y)

tensor([[0.1075, 0.2522, 0.4286],
        [0.3836, 0.4315, 0.9680]])


In [ ]:
y = torch.rand(shape, dtype=torch.double)
print(y)

tensor([[0.9273, 0.5428, 0.8259],
        [0.6298, 0.0765, 0.8690]], dtype=torch.float64)


we cannot call torch.rand for integer functions and if we call doubles it will only retrun float but float64

In [ ]:
# we cannot call torch.rand for integer functions and if we call doubles it will only retrun float
y = torch.randint(1,10,size = shape)
print(y)

tensor([[9, 8, 4],
        [4, 8, 5]])


In [ ]:
tensor1 = torch.randn(2,3)

print(f'Tensor: {tensor1}')
print(f'Shape: {tensor1.shape}')
print(f'Datatype: {tensor1.dtype}')

Tensor: tensor([[ 2.1863,  1.4280, -0.7526],
        [-0.1307, -0.3559, -0.1487]])
Shape: torch.Size([2, 3])
Datatype: torch.float32


In [ ]:
tensor = torch.rand(2,3)

print(f'Tensor: {tensor}')
print(f'Shape: {tensor.shape}')
print(f'Datatype: {tensor.dtype}')

Tensor: tensor([[0.1900, 0.8560, 0.0427],
        [0.9468, 0.7142, 0.3238]])
Shape: torch.Size([2, 3])
Datatype: torch.float32


In [ ]:
x = True

for i in tensor:
  for j in i:
    if j>1:
      x = False
      break

print(x)

True


In [ ]:
x = True

for i in tensor1:
  for j in i:
    if j>1:
      x = False
      break

print(x)

False


In [ ]:
y.dtype, tensor.dtype

(torch.int64, torch.float32)

#building a graph

Goal: `z = x*y` where `y = a+b`

In [ ]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)
x = torch.tensor(3.0, requires_grad=True)
y = a+b
z = y*x
print(z)
print(z.grad_fn)

tensor(9., grad_fn=<MulBackward0>)


In [ ]:
print(y.grad_fn)

In [ ]:
print(a.grad_fn)

None


# Multiplication

In [ ]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[30,40]])
elementwise = a*b
print(elementwise)

tensor([[  5,  12],
        [ 90, 160]])


In [ ]:
# matrix multiplications

matrix = a@b
print(matrix)

tensor([[ 65,  86],
        [135, 178]])


In [ ]:
# reductions



In [ ]:
df = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])