In [1]:
import torch

In [2]:
x = torch.tensor([1,2,3])

In [3]:
print(x)

tensor([1, 2, 3])


In [4]:
x

tensor([1, 2, 3])

In [5]:
shape = (2,3)

ones = torch.ones(shape)
zeros = torch.zeros(shape)

print(f'Ones tensor: \n {ones} \n')
print(f'Zeros tensor: \n {zeros}')

Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
random = torch.rand(shape)
print(random)

tensor([[0.7142, 0.2010, 0.2631],
        [0.2288, 0.8396, 0.5815]])


In [7]:
y = torch.rand(shape, dtype=torch.float)
print(y)

tensor([[0.0608, 0.3074, 0.2166],
        [0.8076, 0.5052, 0.3339]])


In [8]:
y = torch.rand(shape, dtype=torch.double)
print(y)

tensor([[0.8492, 0.3371, 0.0981],
        [0.4805, 0.9295, 0.8724]], dtype=torch.float64)


we cannot call torch.rand for integer functions and if we call doubles it will only retrun float but float64

In [9]:
# we cannot call torch.rand for integer functions and if we call doubles it will only retrun float
y = torch.randint(1,10,size = shape)
print(y)

tensor([[4, 1, 9],
        [9, 2, 9]])


In [10]:
tensor1 = torch.randn(2,3)

print(f'Tensor: {tensor1}')
print(f'Shape: {tensor1.shape}')
print(f'Datatype: {tensor1.dtype}')

Tensor: tensor([[ 0.2134, -1.9110, -0.7656],
        [ 2.1253, -0.4461, -0.8289]])
Shape: torch.Size([2, 3])
Datatype: torch.float32


In [11]:
tensor = torch.rand(2,3)

print(f'Tensor: {tensor}')
print(f'Shape: {tensor.shape}')
print(f'Datatype: {tensor.dtype}')

Tensor: tensor([[0.6988, 0.1698, 0.1745],
        [0.2553, 0.5677, 0.0109]])
Shape: torch.Size([2, 3])
Datatype: torch.float32


In [12]:
x = True

for i in tensor:
  for j in i:
    if j>1:
      x = False
      break

print(x)

True


In [13]:
x = True

for i in tensor1:
  for j in i:
    if j>1:
      x = False
      break

print(x)

False


In [14]:
y.dtype, tensor.dtype

(torch.int64, torch.float32)

#building a graph

Goal: `z = x*y` where `y = a+b`

In [15]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)
x = torch.tensor(3.0, requires_grad=True)
y = a+b
z = y*x
print(z)
print(z.grad_fn)

tensor(9., grad_fn=<MulBackward0>)


In [16]:
print(y.grad_fn)

In [17]:
print(a.grad_fn)

None


# Multiplication

In [18]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[30,40]])
elementwise = a*b
print(elementwise)

tensor([[  5,  12],
        [ 90, 160]])


In [19]:
# matrix multiplications

matrix = a@b
print(matrix)

tensor([[ 65,  86],
        [135, 178]])


In [20]:
# reductions



In [21]:
df = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [22]:
scores = torch.tensor([[10,20,30],
                        [5,10,15]],
                        dtype = torch.float64)
avg_per_assignment = scores.mean(dim = 0)
avg_score_student = scores.mean(dim = 1)
print(avg_per_assignment)
print(avg_score_student)

tensor([ 7.5000, 15.0000, 22.5000], dtype=torch.float64)
tensor([20., 10.], dtype=torch.float64)


In [23]:
# Make all dimentions of the same length always, one can have mutiple rows
# but the columns remians the same!!

# x = torch.tensor([[0,1,2,3,4],
#                   [5,6,7,8],
#                   [9,10,11,12]])

# print(x[:,2])



# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# /tmp/ipykernel_2375/3275909666.py in <cell line: 0>()
# ----> 1 x = torch.tensor([[0,1,2,3,4],
#       2                   [5,6,7,8],
#       3                   [9,10,11,12]])
#       4
#       5 print(x[:,2])

# ValueError: expected sequence of length 5 at dim 1 (got 4)


x = torch.tensor([[0,1,2,3],
                  [5,6,7,8],
                  [9,10,11,12]])

print(x[:,2])

tensor([ 2,  7, 11])


In [24]:
# dim = 1 in rows, dim = 0 in coloumn operations

scores = torch.tensor([[10,20,30],
                        [5,10,60]])

best_indices = torch.argmax(scores, dim = 1)
print(best_indices)


tensor([2, 2])


# Simple linear Regression

`y = XW +b`

X is our input data, W is the weight, b is the bias.
y(y-hat) is our model's prediction or guess.

In [29]:
# craeting a fake data
n=10
# each data have 1 input and 1 output function
D_in = 1
D_out = 1

# create our input data X
X = torch.randn(n, D_in)
print(X)
# Create our true target labels y by using the true W and b
# The true W is 2.0, the 'true' b is 1.0

true_W = torch.tensor([[2.0]])
true_b = torch.tensor(1.0)
y_true = X @ true_W + true_b + torch.randn(n, D_out) * 0.1
print(f'The output tensor is {y_true}')


## you see the part of `torch.randn(n+D_out)*0.1` is actually noise

tensor([[ 0.0974],
        [ 0.7017],
        [ 0.2981],
        [ 0.9738],
        [-0.6070],
        [ 0.5058],
        [ 0.5749],
        [ 0.0254],
        [-0.2021],
        [-0.2246]])
The output tensor is tensor([[ 1.2254],
        [ 2.3587],
        [ 1.4240],
        [ 2.8217],
        [-0.2901],
        [ 1.9775],
        [ 1.9161],
        [ 1.0051],
        [ 0.5655],
        [ 0.7868]])


In [30]:
# Intialize parameters with random values
# Shapes must be correct for matrix multiplication!
W = torch.randn(D_in, D_out,requires_grad= True)
b = torch.randn(1,requires_grad= True)
print(W)
print(b)

tensor([[1.1305]], requires_grad=True)
tensor([-0.5711], requires_grad=True)


In [ ]:
y_hat = model(X_train)
