In [1]:
import torch

In [2]:
x = torch.tensor([1,2,3])

In [3]:
print(x)

tensor([1, 2, 3])


In [4]:
x

tensor([1, 2, 3])

In [5]:
shape = (2,3)

ones = torch.ones(shape)
zeros = torch.zeros(shape)

print(f'Ones tensor: \n {ones} \n')
print(f'Zeros tensor: \n {zeros}')

Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
random = torch.rand(shape)
print(random)

tensor([[0.6883, 0.8625, 0.6513],
        [0.0387, 0.5394, 0.0339]])


In [7]:
y = torch.rand(shape, dtype=torch.float)
print(y)

tensor([[0.6761, 0.9123, 0.4263],
        [0.5048, 0.8183, 0.3114]])


In [8]:
y = torch.rand(shape, dtype=torch.double)
print(y)

tensor([[0.0229, 0.3819, 0.0397],
        [0.0184, 0.9469, 0.9677]], dtype=torch.float64)


we cannot call torch.rand for integer functions and if we call doubles it will only retrun float but float64

In [9]:
# we cannot call torch.rand for integer functions and if we call doubles it will only retrun float
y = torch.randint(1,10,size = shape)
print(y)

tensor([[5, 8, 8],
        [2, 5, 6]])


In [10]:
tensor1 = torch.randn(2,3)

print(f'Tensor: {tensor1}')
print(f'Shape: {tensor1.shape}')
print(f'Datatype: {tensor1.dtype}')

Tensor: tensor([[-0.1132, -2.1072, -0.5829],
        [-0.5400, -0.5006,  0.4462]])
Shape: torch.Size([2, 3])
Datatype: torch.float32


In [11]:
tensor = torch.rand(2,3)

print(f'Tensor: {tensor}')
print(f'Shape: {tensor.shape}')
print(f'Datatype: {tensor.dtype}')

Tensor: tensor([[0.5250, 0.5608, 0.1124],
        [0.9901, 0.4945, 0.1941]])
Shape: torch.Size([2, 3])
Datatype: torch.float32


In [12]:
x = True

for i in tensor:
  for j in i:
    if j>1:
      x = False
      break

print(x)

True


In [13]:
x = True

for i in tensor1:
  for j in i:
    if j>1:
      x = False
      break

print(x)

True


In [14]:
y.dtype, tensor.dtype

(torch.int64, torch.float32)

#building a graph

Goal: `z = x*y` where `y = a+b`

In [15]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)
x = torch.tensor(3.0, requires_grad=True)
y = a+b
z = y*x
print(z)
print(z.grad_fn)

tensor(9., grad_fn=<MulBackward0>)


In [16]:
print(y.grad_fn)

In [17]:
print(a.grad_fn)

None


# Multiplication

In [18]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[30,40]])
elementwise = a*b
print(elementwise)

tensor([[  5,  12],
        [ 90, 160]])


In [19]:
# matrix multiplications

matrix = a@b
print(matrix)

tensor([[ 65,  86],
        [135, 178]])


In [20]:
# reductions



In [21]:
df = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [31]:
scores = torch.tensor([[10,20,30],
                        [5,10,15]],
                        dtype = torch.float64)
avg_per_assignment = scores.mean(dim = 0)
avg_score_student = scores.mean(dim = 1)
print(avg_per_assignment)
print(avg_score_student)

tensor([ 7.5000, 15.0000, 22.5000], dtype=torch.float64)
tensor([20., 10.], dtype=torch.float64)


In [35]:
# Make all dimentions of the same length always, one can have mutiple rows
# but the columns remians the same!!

# x = torch.tensor([[0,1,2,3,4],
#                   [5,6,7,8],
#                   [9,10,11,12]])

# print(x[:,2])



# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# /tmp/ipykernel_2375/3275909666.py in <cell line: 0>()
# ----> 1 x = torch.tensor([[0,1,2,3,4],
#       2                   [5,6,7,8],
#       3                   [9,10,11,12]])
#       4
#       5 print(x[:,2])

# ValueError: expected sequence of length 5 at dim 1 (got 4)


x = torch.tensor([[0,1,2,3],
                  [5,6,7,8],
                  [9,10,11,12]])

print(x[:,2])

tensor([ 2,  7, 11])


In [36]:
# dim = 1 in rows, dim = 0 in coloumn operations

scores = torch.tensor([[10,20,30],
                        [5,10,60]])

best_indices = torch.argmax(scores, dim = 1)
print(best_indices)


tensor([2, 2])


# Simple linear Regression

`y = XW +b`

X is our input data, W is the weight, b is the bias.
y(y-hat) is our model's prediction or guess.

In [ ]:
# craeting a fake data
n=10

D_in = 1
D_out = 1

X = torch.randn(n, D_in)

